server:
  port: 9000
  
spring:
   application:
    name: ShoppingService

resilience4j:
  circuitbreaker:
    instances:
      ShoppingService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      userService:
        max-attempts: 5
        waitDuration: 5s